image: themattrix/tox

##########################################
##########################################
## We have to set the following env vars
## in the admin interface :
## - AWS_DEFAULT_REGION
## - BUCKET_NAME
## - AWS_ACCESS_KEY_ID
## - AWS_SECRET_ACCESS_KEY

stages:
    - tests
    - benchmarks_and_profiling
    - deploy_docs
    - integration_testing
cache:
    paths:
        - .tox

before_script:
    - echo "Setting Up...."

tests:
    stage: tests
    before_script:
        - echo "Setting Up...."
        - apt update
        - apt install -y libgl1-mesa-glx xvfb graphviz xdg-utils libcairo2-dev libjpeg-dev libgif-dev
        - pip install tox
    script:
        - xvfb-run tox -v --recreate


build_and_deploy_docs:
    image: "python:latest"
    stage: deploy_docs
    only:
        - master
    dependencies:
        - tests
    before_script:
        - apt update
        - apt install -y graphviz libgl1-mesa-glx xvfb xdg-utils libcairo2-dev libjpeg-dev libgif-dev
        - pip install tox awscli
    script:
        - echo "Bucket=${BUCKET_NAME}"
        - echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
        - echo "CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}"
        - xvfb-run tox -v -e docs
        - aws s3 cp ./docs/_build/html/ s3://${BUCKET_NAME} --recursive
    environment:
        name: ${CI_COMMIT_REF_SLUG}
        url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/

benchmarks_and_profiling:
    dependencies:
        - tests
    stage: benchmarks_and_profiling
    only:
        variables:
            - $BENCHMARKS_AND_PROFILING
    before_script:
        - apt update
        - apt install -y libgl1-mesa-glx xvfb graphviz xdg-utils libcairo2-dev libjpeg-dev libgif-dev
        - pip install tox
    script:
        - xvfb-run tox -e benchmarks,profiling -v --recreate

test_conda_setup:
    dependencies:
        - tests
    stage: integration_testing
    script:
        - wget -nv https://repo.anaconda.com/archive/Anaconda3-5.3.1-Linux-x86_64.sh -O /tmp/Anaconda3-5.3.1-Linux-x86_64.sh
        - bash /tmp/Anaconda3-5.3.1-Linux-x86_64.sh -b -p /tmp/anaconda3
        - export PATH=/tmp/anaconda3/bin:$PATH; bash getting_started/getting_started.sh

baselines:
    dependencies:
        - tests
    stage: integration_testing
    before_script:
        - apt update
        - apt install -y libgl1-mesa-glx xvfb graphviz xdg-utils libcairo2-dev libjpeg-dev libgif-dev
        - pip install tox

    script:
        - git clone http://gitlab.aicrowd.com/flatland/baselines.git
# inject version of flatland into baseline requirement to have in the tox virtual environment
        - cd baselines; git checkout 42-run-baselines-in-ci; sed -i s'/@master/@${CI_COMMIT_REF_SLUG}/g' requirements_torch_training.txt; xvfb-run tox -v --recreate


